-- sequelize model:create --name usu_vinculo --attributes vin_id:integer,vin_usu_origem:integer,vin_usu_destino:integer,vin_aceito:boolean,vin_alerta:boolean

CREATE TABLE USU_VINCULO (
    VIN_ID INT AUTO_INCREMENT NOT NULL,
    VIN_USU_ORIGEM INT NOT NULL,
    VIN_USU_DESTINO INT NOT NULL,
    VIN_ACEITO BOOLEAN NOT NULL,
    VIN_ALERTA BOOLEAN NOT NULL,
    PRIMARY KEY (VIN_ID),
    FOREIGN KEY (VIN_USU_ORIGEM) REFERENCES USUARIO (USU_ID),
    FOREIGN KEY (VIN_USU_DESTINO) REFERENCES USUARIO (USU_ID)
);

#INSERTS

#USUARIO LUCAS PARA USUARIO GABRIEL COMO STATUS PENDENTE DE ACEITAR O CONVITE
INSERT INTO USU_VINCULO (
    `VIN_USU_ORIGEM`,
    `VIN_USU_DESTINO`,
    `VIN_ACEITO`,
    `VIN_ALERTA`) 
    VALUES(
        1,
        2,
        0,
        1
    );

#USUARIO LUCAS PARA USUARIO JONATHAN COMO STATUS CONVITE ACEITO
INSERT INTO USU_VINCULO (
    `VIN_USU_ORIGEM`,
    `VIN_USU_DESTINO`,
    `VIN_ACEITO`,
    `VIN_ALERTA`) 
    VALUES(
        1,
        3,
        1,
        0
    );

#USUARIO GABRIEL PARA USUARIO JONATHAN COMO STATUS RECUSADO
INSERT INTO USU_VINCULO (
    `VIN_USU_ORIGEM`,
    `VIN_USU_DESTINO`,
    `VIN_ACEITO`,
    `VIN_ALERTA`) 
    VALUES(
        2,
        3,
        0,
        0
    );